apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproject-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudproject-app
  template:
    metadata:
      labels:
        app: cloudproject-app
    spec:
      containers:
      - name: app
        image: cloudproject-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:123@cloudproject-postgres:5432/cloudproject?schema=public"
        - name: JWT_SECRET
          value: "super_secret_key"
        - name: NODE_ENV
          value: "development"          
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_SITE_URL
          value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudproject-app-service
spec:
  selector:
    app: cloudproject-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer                   # 特意改成LoadBalancer 方便 tunnel 访问
