apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproject-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudproject-app
  template:
    metadata:
      labels:
        app: cloudproject-app
    spec:
      containers:
      - name: app
        image: lanskette/cloudproject:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:123@cloudproject-postgres:5432/cloudproject?schema=public"
        - name: JWT_SECRET
          value: "super_secret_key"
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_SITE_URL
          value: "http://146.190.189.176"   
        - name: AUTH_URL
          value: "http://146.190.189.176"
        - name: NEXTAUTH_URL
          value: "http://146.190.189.176"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXTAUTH_URL
          value: "http://146.190.189.176"
        - name: NEXTAUTH_URL_INTERNAL
          value: "http://localhost:3000"
        - name: DISABLE_HTTPS_REDIRECT
          value: "true"
        - name: COOKIE_SECURE
          value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: cloudproject-app-service
spec:
  selector:
    app: cloudproject-app
  ports:
  - protocol: TCP
    port: 80         
    targetPort: 3000 
  type: LoadBalancer